---
language: ruby
rvm:
- 2.0.0

before_script: bundle exec rake hatchet:setup_travis

# Run tests in parallel
script: bundle exec parallel_rspec -n 11 spec/

after_script:
  - heroku keys:remove ~/.ssh/id_rsa

env:
  global:
  - HATCHET_RETRIES=3
  - IS_RUNNING_ON_TRAVIS=true
  - HATCHET_DEPLOY_STRATEGY=git
  # sets the HEROKU_API_KEY to a dummy user for Heroku deploys
  - secure: |-
      ccqb7fKumq2+VEkSrkCqmLjALj5R/ZDgAQGZULSFYeD0O0man3hezUEbMB53
      U+7gLkbqz5saFX9S5Sz26f99vmhWz1bMHkC2UtlyFSlgaqSvXMZNHJAweqRY
      ptqugqtvT0VVl1g3DInVgjDZhjINICv/CIorNuHijOFanP1Zmxg=
