language: ruby
rvm:
- 2.4.4
before_script:
  - gem install bundler -v 1.16.1
  - bundle exec rake hatchet:setup_travis
script: bundle exec parallel_rspec -n 11 spec/$TEST_SUITE
env:
  global:
  - HATCHET_RETRIES=3
  - IS_RUNNING_ON_CI=true
  - HATCHET_DEPLOY_STRATEGY=git
  - HATCHET_APP_LIMIT=80
  - BUILDPACK_LOG_FILE=tmp/buildpack.log
  - secure: xFS5oLPMGyT6N0LKwU7wllaEZEVLzE/D5HuD14q3Vfd4L369XpV6ORYJF/2mkf765m+LH1MaN09rJaKc00ZcQfQECMuzyWagLsr1bVKs+szta3G/nFjjVTwmoPX5kVw5q7e6TYvS/KAzo+n8u5pW+zu8MMTwnv40QI6LfcbZkTc=
  - secure: wd/FBYI9I37PJ+eXhO8vesvWELkklNgGRA1xo/tuA31+ACpY/jG5EjrHd+semsfDTxM8fZe3s0foIch+jeMTIOcGs98tDC/L/8b/h6i0Qic0DqkAk6B30fT+5Nl3dufjiXsBJg5xj1zYqW6ka3DKIDjnn+3ao2cme05MtDQBHdc=
  matrix:
    - TEST_SUITE=helpers/
    - TEST_SUITE=installers/
    - TEST_SUITE=hatchet/bugs_spec.rb
    - TEST_SUITE=hatchet/ci_spec.rb
    - TEST_SUITE=hatchet/jvm_spec.rb
    - TEST_SUITE=hatchet/node_spec.rb
    - TEST_SUITE=hatchet/rails23_spec.rb
    - TEST_SUITE=hatchet/rails3_spec.rb
    - TEST_SUITE=hatchet/rails4_spec.rb
    - TEST_SUITE=hatchet/rails5_spec.rb
    - TEST_SUITE=hatchet/rubies_spec.rb
    - TEST_SUITE=hatchet/ruby_spec.rb
    - TEST_SUITE=hatchet/stack_spec.rb

sudo: false
dist: trusty
addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
