api = "0.2"

[buildpack]
id = "heroku/ruby"
version = "0.1.1"
name = "Ruby"
ruby_version = "2.6.6"

[publish]

[publish.Ignore]
files = ["spec/"]

[[publish.Vendor]]
url = "https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/ruby.tgz"
dir = "."
files = ["./.env"]

[[publish.Vendor]]
url = "https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.6.6.tgz"
dir = "vendor/ruby/heroku-18"

[[publish.Vendor]]
url = "https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.6.6.tgz"
dir = "vendor/ruby/heroku-20"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack"
