[buildpack]
name = "Ruby"
ruby_version = "3.3.8"

[publish.Ignore]
files = [
  "changelogs/",
  "spec/",
  "Gemfile",
  "Gemfile.lock",
  "Rakefile",
  "app.json",
  "hatchet.json",
  "hatchet.lock",
]
